import { nancaluiDarkTheme, nancaluiLightTheme, Theme } from '../theme';
export const infinityTheme: Theme = new Theme({
  id: 'infinity-theme',
  name: '无限主题',
  data: {
    ...nancaluiLightTheme.data,
    'nancalui-brand-foil': '#C8C9CC',
    'nancalui-global-bg': '#F8F8FA',
    'nancalui-base-bg': '#ffffff',
    'nancalui-text': '#000000',
    'nancalui-aide-text': '#71757f',
    'nancalui-placeholder': '#babbc0',
    "nancalui-disabled-text": "#C8C9CC",
    'nancalui-disabled-bg': '#F7F8FA',
    'nancalui-line': '#D7D8DA',
    'nancalui-dividing-line': '#F7F8FA',
    'nancalui-area': '#f5f5f5',
    'nancalui-list-item-hover-bg': '#F7F8FA',
    'nancalui-list-item-active-bg': '#F2F5FC',
    'nancalui-list-item-active-hover-bg': '#F2F5FC',
    'nancalui-list-item-selected-bg': '#EFF1F5',
    'nancalui-list-item-hover-text': '#252b3a',
    'nancalui-list-item-active-text': '#252B3A',
    'nancalui-form-control-line-hover': '#9b9fa8',
    'nancalui-form-control-line': '#D7D8DA',
    'nancalui-form-control-bg': '#ffffff',
    'nancalui-icon-text': '#71757f',
    'nancalui-icon-fill': '#71757f',
    'nancalui-icon-fill-weak': '#babbc0',
    'nancalui-icon-fill-hover': '#252b3a',
    'nancalui-icon-fill-active': '#252b3a',
    'nancalui-icon-fill-active-hover': '#252b3a',
    'nancalui-label-bg': '#F0F7FF',
    'nancalui-border-radius': '4px',
    'nancalui-font-size': '12px',
    'nancalui-font-size-md': '12px',
    'nancalui-font-size-card-title': '16px',
    'nancalui-shadow-length-fullscreen-overlay': '0 0 6px 0',
    'nancalui-border-radius-card': '8px',
    'nancalui-border-radius-full': '100px',
    'nancalui-waiting': '#94DFFF',
    'nancalui-danger-bg': '#ffd5d4',
    'nancalui-shape-icon-fill': '#d7d8da',
    'nancalui-shape-icon-fill-hover': '#babbc0',
    'nancalui-shape-icon-fill-active': '#babbc0',
    'nancalui-shape-icon-fill-disabled': '#F7F8FA',
    'nancalui-btn-padding': '0 16px',
    'nancalui-btn-common-bg': '#ebebeb',
    'nancalui-btn-common-bg-hover': '#d1d1d1',
    'nancalui-btn-common-bg-active': '#bdbdbd',
    'nancalui-btn-common-color-hover': '#252b3a',
    'nancalui-btn-common-color-active': '#252b3a',
    'nancalui-btn-common-border-color': 'transparent',
    'nancalui-btn-common-border-color-hover': 'transparent',
    'nancalui-btn-common-border-color-active': 'transparent',
    'nancalui-btn-sm-padding': '0 16px',
    'nancalui-btn-lg-padding': '0 20px',
  },
  extends: 'nancalui-light-theme',
  isDark: false,
});

export const provenceTheme: Theme = new Theme({
  id: 'provence-theme',
  name: '紫罗兰主题',
  data: {
    ...infinityTheme.data,
    'nancalui-brand': '#7B69EE',
    'nancalui-brand-foil': '#F5F5F9',
    'nancalui-brand-active-focus': '#7B69EE',
    'nancalui-primary-active': '#7B69EE',
    'nancalui-brand-hover': '#7B69EE',
    'nancalui-global-bg': '#f9fafb',
    'nancalui-base-bg': '#ffffff',
    'nancalui-text': '#070036',
    'nancalui-aide-text': '#717087',
    'nancalui-placeholder': '#babbc0',
    "nancalui-disabled-text": "#C8C9CC",
    'nancalui-disabled-bg': '#F7F8FA',
    'nancalui-line': '#E2E2E5',
    'nancalui-dividing-line': '#F7F8FA',
    'nancalui-list-item-hover-bg': '#F5F5F9',
    'nancalui-list-item-active-bg': '#7B69EE',
    'nancalui-list-item-active-hover-bg': '#7B69EE',
    'nancalui-list-item-selected-bg': '#F4F2FF',
    'nancalui-list-item-hover-text': '#252b3a',
    'nancalui-list-item-active-text': '#ffffff',
    'nancalui-form-control-line-hover': '#A3A6AC',
    'nancalui-form-control-line': '#D7D8DA',
    'nancalui-icon-text': '#babbc0',
    'nancalui-brand-active': '#7B69EE',
    'nancalui-primary': '#7B69EE',
    'nancalui-primary-hover': '#7B69EE',
    'nancalui-form-control-line-active': '#7B69EE',
    'nancalui-form-control-line-active-hover': '#7B69EE',
    'nancalui-icon-fill-active': '#7B69EE',
    'nancalui-icon-fill-active-hover': '#7B69EE',
    'nancalui-label-bg': '#F4F2FF',
    'nancalui-embed-search-bg': '#F4F2FF',
    'nancalui-connected-overlay-line': '#7B69EE',
    'nancalui-primary-disabled': '#d8d2fa',
    'nancalui-icon-fill-active-disabled': '#d8d2fa',
  },
  extends: 'infinity-theme',
  isDark: false,
});

export const sweetTheme: Theme = new Theme({
  id: 'sweet-theme',
  name: '蜜糖主题',
  data: {
    ...infinityTheme.data,
    'nancalui-brand': '#ec66ab',
    'nancalui-brand-foil': '#f8f1f5',
    'nancalui-brand-active-focus': '#ec66ab',
    'nancalui-primary-active': '#ec66ab',
    'nancalui-brand-hover': '#ec66ab',
    'nancalui-global-bg': '#f9fafb',
    'nancalui-base-bg': '#ffffff',
    'nancalui-text': '#2f272f',
    'nancalui-aide-text': '#827d82',
    'nancalui-placeholder': '#bdb8bd',
    'nancalui-disabled-text': '#cbcacb',
    'nancalui-disabled-bg': '#f6f6f6',
    'nancalui-line': '#aea6ad',
    'nancalui-dividing-line': '#eae7e9',
    'nancalui-list-item-hover-bg': '#f8f1f5',
    'nancalui-list-item-active-bg': '#ffdcee',
    'nancalui-list-item-active-hover-bg': '#ffdcee',
    'nancalui-list-item-selected-bg': '#ffdcee',
    'nancalui-list-item-hover-text': '#252b3a',
    'nancalui-list-item-active-text': '#252b3a',
    'nancalui-form-control-line-hover': '#A3A6AC',
    'nancalui-form-control-line': '#D7D8DA',
    'nancalui-icon-text': '#babbc0',
    'nancalui-brand-active': '#ec66ab',
    'nancalui-primary': '#ec66ab',
    'nancalui-primary-hover': '#ec66ab',
    'nancalui-form-control-line-active': '#ec66ab',
    'nancalui-form-control-line-active-hover': '#ec66ab',
    'nancalui-icon-fill-active': '#ec66ab',
    'nancalui-icon-fill-active-hover': '#ec66ab',
    'nancalui-label-bg': '#ffdcee',
    'nancalui-embed-search-bg': '#ffdcee',
    'nancalui-connected-overlay-line': '#ec66ab',
    'nancalui-primary-disabled': '#fad1e6',
    'nancalui-icon-fill-active-disabled': '#fad1e6',
  },
  extends: 'infinity-theme',
  isDark: false,
});

export const deepTheme: Theme = new Theme({
  id: 'deep-theme',
  name: '深邃夜空主题',
  data: {
    ...infinityTheme.data,
    'nancalui-brand': '#252b3a',
    'nancalui-brand-foil': '#f3f4f7',
    'nancalui-brand-active-focus': '#252b3a',
    'nancalui-primary-active': '#252b3a',
    'nancalui-brand-active': '#252b3a',
    'nancalui-brand-hover': '#252b3a',
    'nancalui-global-bg': '#f7f8fa',
    'nancalui-base-bg': '#ffffff',
    'nancalui-text': '#252b3a',
    'nancalui-aide-text': '#505c7c',
    'nancalui-placeholder': '#9ba6bf',
    'nancalui-disabled-text': '#a8b1c7',
    'nancalui-disabled-bg': '#f7f8fa',
    'nancalui-line': '#cdd2df',
    'nancalui-dividing-line': '#e6e9ef',
    'nancalui-list-item-hover-bg': '#f3f4f7',
    'nancalui-list-item-active-bg': '#252b3a',
    'nancalui-list-item-active-hover-bg': '#252b3a',
    'nancalui-list-item-selected-bg': '#252b3a',
    'nancalui-list-item-hover-text': '#252b3a',
    'nancalui-list-item-active-text': '#ffffff',
    'nancalui-form-control-line-hover': '#A3A6AC',
    'nancalui-form-control-line': '#D7D8DA',
    'nancalui-icon-text': '#babbc0',
    'nancalui-primary': '#252b3a',
    'nancalui-primary-hover': '#252b3a',
    'nancalui-form-control-line-active': '#252b3a',
    'nancalui-form-control-line-active-hover': '#252b3a',
    'nancalui-icon-fill-active': '#252b3a',
    'nancalui-icon-fill-active-hover': '#252b3a',
    'nancalui-connected-overlay-line': '#252b3a',
    'nancalui-primary-disabled': '#bebfc4',
    'nancalui-icon-fill-active-disabled': '#bebfc4',
  },
  extends: 'infinity-theme',
  isDark: false,
});

export const galaxyTheme: Theme = new Theme({
  id: 'galaxy-theme',
  name: '追光主题',
  data: {
    ...nancaluiDarkTheme.data,
    'nancalui-brand-foil': '#F7F8FA',
    'nancalui-global-bg': '#000000',
    'nancalui-base-bg': '#1F1F1F',
    'nancalui-text': '#F5F5F5',
    'nancalui-aide-text': '#A3A3A3',
    'nancalui-placeholder': '#616161',
    'nancalui-disabled-text': '#838383',
    'nancalui-disabled-bg': '#3F3F3F',
    'nancalui-line': '#565656',
    'nancalui-dividing-line': '#303030',
    'nancalui-list-item-hover-bg': '#313131',
    'nancalui-list-item-active-bg': '#30333D',
    'nancalui-list-item-active-hover-bg': '#30333D',
    'nancalui-list-item-selected-bg': '#30333D',
    'nancalui-list-item-hover-text': '#F5F5F5',
    'nancalui-list-item-active-text': '#2F5CD6',
    'nancalui-primary-disabled': '#3f3f3f',
    'nancalui-form-control-bg': '#292a2e',
    'nancalui-form-control-line': '#565656',
    'nancalui-icon-text': '#A3A3A3',
    'nancalui-connected-overlay-bg': '#282828',
    'nancalui-fullscreen-overlay-bg': '#282828',
    'nancalui-warning-line': '#FFDCA3',
    'nancalui-warning-bg': '#4b2e14',
    'nancalui-success-line': '#75EBC2 ',
    'nancalui-success-bg': '#123d32',
    'nancalui-danger-line': '#9f4844',
    'nancalui-danger-bg': '#4a2120',
    'nancalui-info-line': '#3c5091',
    'nancalui-info-bg': '#1c2543',
    'nancalui-default-bg': '#313131',
    'nancalui-border-radius': '4px',
    'nancalui-font-size': '12px',
    'nancalui-font-size-md': '12px',
    'nancalui-font-size-card-title': '16px',
    'nancalui-shadow-length-fullscreen-overlay': '0 0 6px 0',
    'nancalui-border-radius-card': '4px',
  },
  extends: 'nancalui-dark-theme',
  isDark: true,
});
