export default {
  // 基础变量
  'nancalui-global-bg': '#f3f6f8',
  'nancalui-global-bg-normal': '#ffffff',
  'nancalui-base-bg': '#ffffff',
  'nancalui-base-bg-dark': '#333854',
  'nancalui-brand': '#447DFD',
  'nancalui-brand-foil': '#859bff',
  'nancalui-brand-hover': '#6E9EFF',
  'nancalui-brand-active': '#2F5CD6',
  'nancalui-brand-active-focus': '#0069AF',
  'nancalui-contrast': '#F63838',
  'nancalui-text': '#252b3a',
  'nancalui-text-weak': '#575d6c',
  'nancalui-aide-text': '#8a8e99',
  'nancalui-aide-text-stress': '#575d6c',
  'nancalui-placeholder': '#8a8e99',
  'nancalui-light-text': '#ffffff',
  'nancalui-dark-text': '#252b3a',
  'nancalui-link': '#2F5CD6',
  'nancalui-link-active': '#2F5CD6',
  'nancalui-link-light': '#67C7FF',
  'nancalui-link-light-active': '#94DFFF',
  'nancalui-line': '#C8C9CC',
  'nancalui-dividing-line': '#e1e1e1',
  'nancalui-block': '#ffffff',
  'nancalui-area': '#f8f8f8',
  'nancalui-danger': '#f66f6a',
  'nancalui-warning': '#fac20a',
  'nancalui-waiting': '#9faad7',
  'nancalui-success': '#50d4ab',
  'nancalui-info': '#447DFD',
  'nancalui-initial': '#F0F7FF',
  'nancalui-unavailable': '#F7F8FA',
  'nancalui-shadow': 'rgba(0, 0, 0, 0.2)',
  'nancalui-light-shadow': 'rgba(0, 0, 0, 0.1)',
  // 图标
  'nancalui-icon-text': '#252b3a',
  'nancalui-icon-bg': '#ffffff',
  'nancalui-icon-fill': '#d3d5d9',
  'nancalui-icon-fill-hover': '#adb5ce',
  'nancalui-icon-fill-active': '#447DFD',
  'nancalui-icon-fill-active-hover': '#2F5CD6',
  // 表单
  'nancalui-form-control-line': '#C8C9CC',
  'nancalui-form-control-line-hover': '#575d6c',
  'nancalui-form-control-line-active': '#447DFD',
  'nancalui-form-control-line-active-hover': '#0069AF',
  'nancalui-list-item-active-bg': '#447DFD',
  'nancalui-list-item-active-text': '#ffffff',
  'nancalui-list-item-active-hover-bg': '#2F5CD6',
  'nancalui-list-item-hover-bg': '#f2f5fc',
  'nancalui-list-item-hover-text': '#2F5CD6',
  'nancalui-list-item-selected-bg': '#F0F7FF',
  'nancalui-list-item-strip-bg': '#f2f5fc',
  // 禁用
  'nancalui-disabled-bg': '#F7F8FA',
  'nancalui-disabled-line': '#e1e1e1',
  'nancalui-disabled-text': '#C8C9CC',
  'nancalui-primary-disabled': '#94DFFF',
  'nancalui-icon-fill-active-disabled': '#94DFFF',
  // 特殊背景色
  'nancalui-label-bg': '#eef0f5',
  'nancalui-connected-overlay-bg': '#ffffff',
  'nancalui-connected-overlay-line': '#2F5CD6',
  'nancalui-fullscreen-overlay-bg': '#ffffff',
  'nancalui-feedback-overlay-bg': '#464d6e',
  'nancalui-feedback-overlay-text': '#e1e1e1',
  'nancalui-embed-search-bg': '#f2f5fc',
  'nancalui-embed-search-bg-hover': '#eef0f5',
  'nancalui-float-block-shadow': 'rgba(94, 124, 224, 0.3)',
  'nancalui-highlight-overlay': 'rgba(255, 255, 255, 0.8)',
  'nancalui-range-item-hover-bg': '#F0F7FF',
  // 按钮
  'nancalui-primary': '#447DFD',
  'nancalui-primary-hover': '#6E9EFF',
  'nancalui-primary-active': '#0069AF',
  'nancalui-contrast-hover': '#d64a52',
  'nancalui-contrast-active': '#E72B2D',
  // 状态
  'nancalui-danger-line': '#f66f6a',
  'nancalui-danger-bg': '#ffeeed',
  'nancalui-warning-line': '#fa9841',
  'nancalui-warning-bg': '#fff3e8',
  'nancalui-info-line': '#447DFD',
  'nancalui-info-bg': '#f2f5fc',
  'nancalui-success-line': '#75EBC2',
  'nancalui-success-bg': '#edfff9',
  'nancalui-primary-line': '#447DFD',
  'nancalui-primary-bg': '#f2f5fc',
  'nancalui-default-line': '#447DFD',
  'nancalui-default-bg': '#f3f6f8',
  // 字体设置相关
  'nancalui-font-size': '12px',
  'nancalui-font-size-card-title': '16px',
  'nancalui-font-size-page-title': '16px',
  'nancalui-font-size-modal-title': '18px',
  'nancalui-font-size-price': '20px',
  'nancalui-font-size-data-overview': '24px',
  'nancalui-font-size-icon': '16px',
  'nancalui-font-size-sm': '12px',
  'nancalui-font-size-md': '12px',
  'nancalui-font-size-lg': '16px',
  'nancalui-font-title-weight': 'bold',
  'nancalui-font-content-weight': 'normal',
  'nancalui-line-height-base': '1.5',
  // 圆角
  'nancalui-border-radius': '2px',
  'nancalui-border-radius-feedback': '4px',
  'nancalui-border-radius-card': '6px',
  // 阴影
  'nancalui-shadow-length-base': '0 1px 4px 0',
  'nancalui-shadow-length-slide-left': '-2px 0 8px 0',
  'nancalui-shadow-length-slide-right': '2px 0 8px 0',
  'nancalui-shadow-length-connected-overlay': '0 2px 8px 0',
  'nancalui-shadow-length-hover': '0 4px 16px 0',
  'nancalui-shadow-length-feedback-overlay': '0 4px 16px 0',
  'nancalui-shadow-fullscreen-overlay': '0 8px 40px 0',
  // 动效
  'nancalui-animation-duration-slow': '300ms',
  'nancalui-animation-duration-base': '200ms',
  'nancalui-animation-duration-fast': '100ms',
  'nancalui-animation-ease-in': 'cubic-bezier(0.5, 0, 0.84, 0.25)',
  'nancalui-animation-ease-out': 'cubic-bezier(0.16, 0.75, 0.5, 1)',
  'nancalui-animation-ease-in-out': 'cubic-bezier(0.5, 0.05, 0.5, 0.95)',
  'nancalui-animation-ease-in-smooth': 'cubic-bezier(0.645, 0.045, 0.355, 1)',
  'nancalui-animation-linear': 'cubic-bezier(0, 0, 1, 1)',
  // zIndex
  'nancalui-z-index-full-page-overlay': '1080',
  'nancalui-z-index-pop-up': '1060',
  'nancalui-z-index-dropdown': '1062',
  'nancalui-z-index-modal': '1070',
  'nancalui-z-index-drawer': '1040',
  'nancalui-z-index-framework': '1000',
};
